- name: Docker installation
  hosts: all
  become: true
  tasks:
  - name: Update all packages
    apt: update_cache=yes force_apt_get=yes

  - debug:
      msg: "{{ansible_user_id}}"

  - name: Install dependencies
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present

  - name: Get release
    shell: lsb_release -cs
    register: release

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ release.stdout }} stable

  - name: Update all packages and install docker
    apt:
      update_cache: yes
      force_apt_get: yes
      name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

  - name: Post installation docker
    shell: usermod -aG docker {{ansible_env.SUDO_USER}}

